[package]
name = "promql"
version = "0.5.0"
edition = "2024"

[dependencies]
quick-error = "2.0"
nom = "7.0"
builder-pattern = "0.3"
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[features]
default = []
serde = ["dep:serde", "dep:serde_derive"]
